vive(X,Y,Z):-
	X=Y.
viveMayor(X,Y,Z):-
	X>Y.
viveMenor(X,Y,Z):-
	X<Y.
bird(pigeon).
bird(penguin).
lives(pigeon,_).
lives(penguin,antarctica).
lives(penguin,argentina).
lives(penguin,australia).
lives(penguin,chile).
lives(gorrion,alemania).
