vive(X,Y):-
	=(paloma,paloma).
bird(pigeon).
bird(penguin).
lives(pigeon,_).
lives(penguin,antarctica).
lives(penguin,argentina).
lives(penguin,australia).
lives(penguin,chile).
lives(gorrion,alemania).
